mod simpson_quadrature_double_integral;
pub use simpson_quadrature_double_integral::SimpsonQuadratureDoubleIntegral;
mod simpson_quadrature_triple_integral;
pub use simpson_quadrature_triple_integral::SimpsonQuadratureTripleIntegral;
mod simpson_range;
mod utils;
